### ISSUE TITLE
fail to build on ubuntu 16.04

### ISSUE THREAD

**Issue by cmatomic** [erikd/cardano-linux-pkg#1]
```
 cmtomic@pc:~/Transferências/cardano-linux-pkg-master$ make results/run-daedalus.sh results/Daedalus-linux-x64/LICENSE
cp -f scripts/run-daedalus.sh results/run-daedalus.sh
cp: impossível criar o ficheiro regular 'results/run-daedalus.sh': Ficheiro ou directoria inexistente
Makefile:30: recipe for target 'results/run-daedalus.sh' failed
make: *** [results/run-daedalus.sh] Error 1
cmatomic@pc:~/Transferências/cardano-linux-pkg-master$  
```

**Comment by erikd** [comment]
Would you be able to translate that for me?

**Comment by erikd** [comment]
I think the current version should actually work.

**Comment by cmatomic** [comment]
`make: *** [stamp/cabal-update] Error 1`
[TreminalOutPunt.txt](https://github.com/erikd/cardano-linux-pkg/files/1596170/TreminalOutPunt.txt)

**Comment by erikd** [comment]
Try running `mkdir stamp` and running `make` again.

**Comment by cmatomic** [comment]
make: *** [tools/bin/mafia] Error 1
[TreminalOutPunt.txt](https://github.com/erikd/cardano-linux-pkg/files/1596209/TreminalOutPunt.txt)

**Comment by cmatomic** [comment]
seems to be a permissions problem, I had to create several folders to continue compiling

**Comment by erikd** [comment]
Yeah, I need to do a clean check out and then test this.

**Comment by cmatomic** [comment]
file not found  after compiling
```
cmatomic@pc:~/cardano-linux-pkg$ cd results/ && build-certificates-unix.sh
build-certificates-unix.sh: command not found
```
```
cmatomic@pc:~/cardano-linux-pkg/results$ ls
cardano-launcher  cardano-node  cardano-noode  Daedalus-linux-x64  run-daedalus.sh
```

**Comment by erikd** [comment]
You don't seem to have the latest version. Please run `git pull`. Make sure the HEAD commit is 8dd4818f24 .

**Comment by erikd** [comment]
Its still broken :<.

**Comment by erikd** [comment]
Please retry with git commit f01bd9293597d7493fd0ab8c555dc89ab4b30d0e .

**Comment by cmatomic** [comment]
```
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling (exit code: 1)
Makefile:157: recipe for target 'tools/bin/jenga' failed
make: *** [tools/bin/jenga] Error 1
```
[TreminalOutPunt.txt](https://github.com/erikd/cardano-linux-pkg/files/1603036/TreminalOutPunt.txt)

**Comment by erikd** [comment]
I'm pretty sure that is an incorrect GHC version. It must be 8.0.2.

**Comment by cmatomic** [comment]
yes it is ubuntu 16.04  is  ghc 7.10.3-7

**Comment by erikd** [comment]
There is a PPA ( https://launchpad.net/~hvr/+archive/ubuntu/ghc ) with other versions.

**Comment by cmatomic** [comment]
After installing the ppa mentioned above, I had to create symbolic links because the installation packages are installed in the / opt directory.
So it would not be possible the script that you created to detect the installed version because it had created the symbolic links in my home directory.

after that I created a symlink in the directory / usr / bin

**Comment by erikd** [comment]
The latest version (be86ac51dceb) is less insane about paths and validates the ghc and cabal versions.

It would probably be a good idea to do ` git pull` on a regular basis :).

**Comment by cmatomic** [comment]
```
GHC version: 8.0.2
(cd source/cardano-sl/ && git add .gitmodules submods && git commit -m "Add submodules" -- . )

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'cmatomic@pc.(none)')
Makefile:130: recipe for target 'source/cardano-sl/.jenga' failed
make: *** [source/cardano-sl/.jenga] Error 128
```

**Comment by erikd** [comment]
Sorry, this build script is still very much a work-in-progress.

I need to come up with a fix for that, but for now `rm -rf source stamp` and then `make`.

**Comment by erikd** [comment]
Will get some time to work on this over the weekend. Plan to do a clean build in a fresh VM to make sure it works.

**Comment by erikd** [comment]
Assuming its ok to close this.
