### ISSUE TITLE
build issues with ubuntu 16.04

### ISSUE THREAD

**Issue by ljackson** [erikd/cardano-linux-pkg#3]
latest of your repo commit 8dd4818

two fails so far just figured I would give you a heads up thanks for taking this on really want to build on linux;)

appears that mafia wants to install into tools/bin but the directory doesn't exist the makefile creates bin dir rather than tools/bin for copy of mafia binary.

after mkdir -p tools/bin it progresses to building jenga but gets a failed dependency error:

Current branch master is up to date.
(cd source/jenga && mafia build)
Installing dependencies...
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: jenga-0.1.1.0 (user goal)
rejecting: jenga-0.1.1.0:!test (global constraint requires opposite flag
selection)
trying: jenga-0.1.1.0:*test
trying: hedgehog-0.5.1 (dependency of jenga-0.1.1.0:*test)
next goal: mtl (dependency of hedgehog-0.5.1)
rejecting: mtl-2.2.1/installed-3af... (conflict: mtl =>
transformers==0.4.2.0/installed-814..., hedgehog => transformers>=0.5 && <0.6)
rejecting: mtl-2.2.1 (avoiding to reinstall a package with same version but
new dependencies)
trying: mtl-2.2.0.1
next goal: transformers (dependency of jenga-0.1.1.0)
rejecting: transformers-0.4.2.0/installed-814... (conflict: hedgehog =>
transformers>=0.5 && <0.6)
rejecting: transformers-0.5.5.0, 0.5.4.0, 0.5.2.0, 0.5.1.0, 0.5.0.1, 0.5.0.0
(conflict: mtl => transformers==0.4.*)
rejecting: transformers-0.4.3.0, 0.4.2.0, 0.4.1.0 (conflict: hedgehog =>
transformers>=0.5 && <0.6)
rejecting: transformers-0.3.0.0, 0.2.2.1, 0.2.1.0, 0.2.0.0, 0.1.4.0, 0.1.3.0,
0.1.1.0, 0.1.0.1, 0.0.1.0, 0.0.0.0 (conflict: jenga => transformers>=0.4 &&
<0.7)
rejecting: transformers-0.5.3.1, 0.5.3.0, 0.5.0.2 (conflict: mtl =>
transformers==0.4.*)
rejecting: transformers-0.4.0.0 (conflict: hedgehog => transformers>=0.5 &&
<0.6)
rejecting: transformers-0.2.2.0, 0.1.0.0 (conflict: jenga => transformers>=0.4
&& <0.7)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling (exit code: 1)
Makefile:165: recipe for target 'tools/bin/jenga' failed
make: *** [tools/bin/jenga] Error 1

Again thanks for your time working this out.

**Comment by erikd** [comment]
Yeah, looks like I announced this way too early.

The first issue is definitely something I am aware. The second though, seems to be due to a wrong version of ghc. Can you check that you have ghc version 8.0.2 ?

**Comment by ljackson** [comment]
No just used the build in distro's haskell-platform metapackage that appears to have installed 7.10.3 ghc might make normal distro stuff harder any thoughts on a docker image for the build env to have 8.0.2?

Thanks again for the effort to get this working...

**Comment by erikd** [comment]
Cardano/Daedalus are difficult enough to build with a single GHC version that its currently *way* too early to make it buildable with more than one version.

Thanks for the thanks though. I really do want to make this a reliable way to build this thing. Unfortunately I'm  back at work this week and hence have much less time to work on it.

**Comment by ljackson** [comment]
so using the PPA https://launchpad.net/~hvr/+archive/ubuntu/ghc i switched too ghc 8.0.2 and cabal 1.24.0.2 i had to add to the Makefile PATH it's path /opt/ghc/bin as your overriding env ? What versions do you use?

**Comment by erikd** [comment]
Not too sure what to do with `PATH`. The intention was to keep it clean to avoid problems with odd things the user may have on their default `PATH`. Let me think about it some more.

Yeah, ghc 8.0.2 and cabal-install version 1.24.* is what you need. However please note that I'm pretty sure this build script is currently broken. It should be back to working in the next 24 or so hours.

**Comment by erikd** [comment]
Please retry with git commit f01bd9293597d7493fd0ab8c555dc89ab4b30d0e .

**Comment by ljackson** [comment]
testing I removed the haskell-platform metapackage and manually linked ghc cabal ..etc into /usr/bin but seems like dep check and /opt/ghc/bin if ubuntu might make it eaiser? Will update once build attempt completes. Thx!

**Comment by erikd** [comment]
Yeah, I should do something about that PATH issue.

**Comment by ljackson** [comment]
ok so got it too build may have missed something but above plus had to build rocksdb from source with cmake and install as dist rocksdb is incompat.

also

cp ./home/.mafia/packages/2/x86_64-unknown-linux/8.0.2/markdown-unlit-0.5.0-b0951cf999551b4a46627551ca6fca4e82895d37/bin/markdown-unlit tools/bin/
cp ./home/.mafia/packages/2/x86_64-unknown-linux/8.0.2/autoexporter-1.1.2-6ed45aff71a31b8d83e96b1f30eb04a2f1786943/bin/autoexporter tools/bin/

as they were not found by scripts

then after succss on build to setup I had to run script using bash as /bin/sh isn't really bash on unbuntu

(cd results/ && bash ./build-certificates-unix.sh)

then it worked and is syncing mainnet! 

thanks again will see if it works correctly/play around with it... let you know if I hit anything else odd...

**Comment by erikd** [comment]
Will doe something about `autoexporter` and `markdown-unlit`. Thanks!

**Comment by erikd** [comment]
The issue with `autoexporter` and `markdown-unlit` is now fixed.

**Comment by erikd** [comment]
Original issues seem to have been fixed. Closing this.
