### ISSUE TITLE
cabal:could not resolve dependencies

### ISSUE THREAD

**Issue by shuj71** [erikd/cardano-linux-pkg#4]
make
mkdir -p results
(cd source/cardano-sl/tools && mafia build cardano-launcher)
Writing a default package environment file to
/home/rory/cardano-linux-pkg/cardano-linux-pkg/source/cardano-sl/tools/cabal.sandbox.config
Creating a new sandbox at
/home/rory/cardano-linux-pkg/cardano-linux-pkg/source/cardano-sl/tools/.cabal-sandbox/x86_64-unknown-linux/7.10.3
Creating sandbox for polyparse-1.12-d75564f476f7dea2c4c3c8991b0a23e03942ebd3
Waiting for polyparse-1.12-d75564f476f7dea2c4c3c8991b0a23e03942ebd3
Building polyparse-1.12-d75564f476f7dea2c4c3c8991b0a23e03942ebd3
Resolving dependencies...
Notice: installing into a sandbox located at
/home/rory/cardano-linux-pkg/cardano-linux-pkg/home/.mafia/packages/2/x86_64-unknown-linux/7.10.3/polyparse-1.12-d75564f476f7dea2c4c3c8991b0a23e03942ebd3
Configuring polyparse-1.12...
Building polyparse-1.12...
Installed polyparse-1.12
Creating sandbox for cpphs-1.20.8-395dfc11c01924827d99624701f77d3e9577f700
Building cpphs-1.20.8-395dfc11c01924827d99624701f77d3e9577f700
Resolving dependencies...
Notice: installing into a sandbox located at
/home/rory/cardano-linux-pkg/cardano-linux-pkg/home/.mafia/packages/2/x86_64-unknown-linux/7.10.3/cpphs-1.20.8-395dfc11c01924827d99624701f77d3e9577f700
Configuring cpphs-1.20.8...
Building cpphs-1.20.8...
Installed cpphs-1.20.8
Installing dependencies...
Warning:
/home/rory/cardano-linux-pkg/cardano-linux-pkg/source/cardano-sl/submods/swagger2/swagger2.cabal:
Ignoring unknown section type: custom-setup
Warning:
/home/rory/cardano-linux-pkg/cardano-linux-pkg/source/cardano-sl/submods/swagger2/swagger2.cabal:
Ignoring unknown section type: custom-setup
Warning:
/home/rory/cardano-linux-pkg/cardano-linux-pkg/source/cardano-sl/submods/swagger2/swagger2.cabal:
Ignoring unknown section type: custom-setup
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: cardano-sl-tools-1.0.3 (user goal)
trying: base-4.8.2.0/installed-0d6... (dependency of cardano-sl-tools-1.0.3)
next goal: cardano-report-server (dependency of cardano-sl-tools-1.0.3)
rejecting: cardano-report-server-0.4.0 (conflict:
base==4.8.2.0/installed-0d6..., cardano-report-server => base>=4.9.0.0 &&
<5.0.0.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling --constraint cardano-sl-auxx == 1.0.3 --constraint cardano-sl-binary == 1.0.3 --constraint cardano-sl-block == 1.0.3 --constraint cardano-sl-client == 1.0.3 --constraint cardano-sl-core == 1.0.3 --constraint cardano-sl-crypto == 1.0.3 --constraint cardano-sl-db == 1.0.3 --constraint cardano-sl-delegation == 1.0.3 --constraint cardano-sl-explorer == 1.0.3 --constraint cardano-sl-generator == 1.0.3 --constraint cardano-sl-infra == 1.0.3 --constraint cardano-sl == 1.0.3 --constraint cardano-sl-lrc == 1.0.3 --constraint cardano-sl-networking == 1.0.3 --constraint cardano-sl-node == 1.0.3 --constraint cardano-sl-ssc == 1.0.3 --constraint acid-state == 0.14.2 --constraint canonical-json == 0.5.0.0 --constraint cardano-crypto == 1.0.0 --constraint cardano-report-server == 0.4.0 --constraint binary-serialise-cbor == 0.1.1.0 --constraint cbor-tool == 0.1.0.0 --constraint cborg == 0.1.1.0 --constraint cborg-json == 0.1.0.0 --constraint serialise == 0.1.0.0 --constraint dns == 3.0.0 --constraint engine-io == 1.2.15 --constraint engine-io-snap == 1.0.4 --constraint engine-io-wai == 1.0.6 --constraint engine-io-yesod == 1.0.4 --constraint binary-example == 1.0.0 --constraint chat == 1.0.0 --constraint latency == 1.0.0 --constraint socket-io == 1.3.7 --constraint ed25519 == 0.0.5.0 --constraint kademlia == 1.1.0.1 --constraint network-transport == 0.5.2 --constraint network-transport-inmemory == 0.5.1 --constraint network-transport-tcp == 0.5.1 --constraint plutus-prototype == 0.1.0.0 --constraint swagger2 == 2.1.4.1 --constraint time-units == 1.0.0 --constraint cardano-sl-txp == 1.0.3 --constraint cardano-sl-update == 1.0.3 --constraint cardano-sl-util == 1.0.3 --constraint cardano-sl-wallet == 1.0.3 --constraint cardano-sl-wallet-new == 0.1.0.0 (exit code: 1)
Makefile:117: recipe for target 'results/cardano-launcher' failed
make: *** [results/cardano-launcher] Error 1

It seems like there's a version conflict in base, it's looking for 4.9 and finding 4.8.2. Hope this helps.

**Comment by erikd** [comment]
Looks like you're using an incompatible version of GHC. Currently this *requires* ghc 8.0.2. I would like to make this compatible with other versions, but for now this is not possible,

**Comment by erikd** [comment]
Assuming its ok to close this.
