### ISSUE TITLE
Makefile:191: recipe for target 'stamp/cabal-update' failed

### ISSUE THREAD

**Issue by tanzeelrana** [erikd/cardano-linux-pkg#5]
tanzeelrana@tanzeelrana-HP-Compaq-dx7500-SFF:~/cardano-linux-pkg$ make 
mkdir -p stamp
scripts/git-sync-repo.sh https://github.com/input-output-hk/cardano-sl.git source/cardano-sl
Cloning into 'source/cardano-sl'...
remote: Counting objects: 148798, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 148798 (delta 9), reused 7 (delta 5), pack-reused 148760
Receiving objects: 100% (148798/148798), 80.16 MiB | 1.25 MiB/s, done.
Resolving deltas: 100% (107427/107427), done.
Checking connectivity... done.
touch stamp/cardano-source
scripts/ghc-version-check.sh
Unsupported GHC version : 7.10.3
Makefile:191: recipe for target 'stamp/cabal-update' failed
make: *** [stamp/cabal-update] Error 1

**Comment by erikd** [comment]
> Unsupported GHC version : 7.10.3

At the top of the Makefile, it says `ghc-8.0.2`. I'd like to be able to relax those bounds, but its not working yet.

If you are on Ubuntu, HVR's PPA (https://launchpad.net/~hvr/+archive/ubuntu/ghc) has the required versions of GHC and cabal-install.

**Comment by erikd** [comment]
Assuming its ok to close this.
