### ISSUE TITLE
Makefile:125: recipe for target 'tools/bin/cardano-wallet-hs2purs' failed

### ISSUE THREAD

**Issue by SJablonska** [erikd/cardano-linux-pkg#6]
Hi,
My system: Debian stretch, latest updates.

I am getting the following error:

mkdir -p tools/bin/
(cd source/cardano-sl/wallet && mafia build cardano-wallet-hs2purs)
Preprocessing library cardano-sl-wallet-1.0.3...
Preprocessing executable 'cardano-wallet-hs2purs' for
cardano-sl-wallet-1.0.3...
Linking dist/build/cardano-wallet-hs2purs/cardano-wallet-hs2purs ...
/usr/bin/ld.gold: error: dist/build/cardano-wallet-hs2purs/cardano-wallet-hs2purs-tmp/PSTypes.o: file is empty
dist/build/cardano-wallet-hs2purs/cardano-wallet-hs2purs-tmp/Main.o(.data+0x45c0): error: undefined reference to 'PSTypes_psInt53_closure'
dist/build/cardano-wallet-hs2purs/cardano-wallet-hs2purs-tmp/Main.o(.data+0x45f0): error: undefined reference to 'PSTypes_psPosixTime_closure'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
Process failed: cabal build -j --ghc-options=-Werror cardano-wallet-hs2purs (exit code: 1)
Makefile:125: recipe for target 'tools/bin/cardano-wallet-hs2purs' failed
make: *** [tools/bin/cardano-wallet-hs2purs] Error 1

**Comment by erikd** [comment]
Current git HEAD of the upstream cardano-sl repo doesn't work. I'm working on getting a previous commit working.

**Comment by SJablonska** [comment]
Thanks!

**Comment by erikd** [comment]
@SJablonska If you pull my latest updates to this repo and then do:
```
make purge-cardano
make
```
it should work.

**Comment by SJablonska** [comment]
Thanks!
Cloning now. will keep you informed

**Comment by SJablonska** [comment]
Working! Great!

Couple of questions:
1) The wallet title is Daedalus (dev). I assume it is safe to hold the tokens?
2) Can I change the datadir? If so, how?

Thanks for all the help Erik.

Steve

**Comment by erikd** [comment]
1. I've been using this version to hold my ADA. Even if the wallet screws up, it should always be possible to restore it using the 12 (I think) word recovery phrase.

2. I haven't tried this, but it should be possible by just editing the `run-daedalus.sh` script and modifying `CFGDIR`.

3. JUst copy the complete `results/` directory to the other box (assuming its running a similar version of Linux) and it should just work.

**Comment by SJablonska** [comment]
Thanks!
