### ISSUE TITLE
build-certificates-unix.sh premature optimization is the root of all evil

### ISSUE THREAD

**Issue by grummerd** [erikd/cardano-linux-pkg#8]
In section 2/10, on the line containing (i'm using [Ubuntu server v18.04] Linux, not Darwin)

    sed -i "s/OPENSSL_MD/${MD}/g" {ca,client,server}.conf

Gets the following error

    sed: can't read {ca,client,server}.conf
    No such file or directory

Here is the fix

    sed -i "s/OPENSSL_MD/${MD}/g" ca.conf client.conf server.conf

Seems the curly brackets optimization doesn't work. And it's unnecessary

Tested and this seems to fix the issue

**Comment by erikd** [comment]
This script is actually part of the upstream sources and hence not something that should be fixed here.
