### ISSUE TITLE
build-certificates-unix.sh execute permissions

### ISSUE THREAD

**Issue by grummerd** [erikd/cardano-linux-pkg#9]
Permissions are read write

    chmod +x ./build-certificates-unix.sh

**Comment by erikd** [comment]
Current permissions were a conscious decision.  DO not want this script executed accidentally.

**Comment by grummerd** [comment]
Wait! Worst case scenerio. So new CA root certificate is created. Not the end of the world right?! Plus their certificates timeout after ~3000+ days anyways. So eventually the grandkids will need to reissue the certs

right?? I'm not seeing the downside

Anyways In this project's readme.md should add the instruction to run the chmod +x command. Unless u feel it's too super obvious
